@startuml _tous

title Diagramme de classe

!$all=1
!includesub legend.puml!legend

package game {
	!$with_cell="true"
	!includesub grid.puml!grid

	!includesub error.puml!error

	!includesub move.puml!move

	!includesub coord.puml!coord

	!includesub game.puml!game
}

G -[hidden]down- Game
Coord -[hidden]down- Move

center footer "Prend en compte l'organisation des packages"

@enduml
